# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

repos:
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    - id: isort
      additional_dependencies: [toml]
-   repo: https://github.com/PyCQA/flake8
    rev: '5.0.2'
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear>=22.1.11,
        flake8-logging-format,
        flake8-2020==1.6.1,
      ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
