# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - |
    pip install -r Requirements.txt
    pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist
  user: __token__
  password:
    secure: sZNVn05vkSfi6Ia30gMXi/TKEb38ATPJeIBkP1a28DghQ67vPhHtTJNGAr2j1jgoSKnG4zVHdeKC24VVNLvnMrbDsgE0zBEC45Q66ZWxF0fSIoJrm3YJAaDqFexNTeCNyAgf9qnyFHomCUTtJs+TCsYqaMBdEgqpqkfHLb2WCd2m7xlxR0Qu4XlAhtJ+JFF4cbMuQG3ZQ+qSAg+Cx7lp/V/uHuMf0P538CXg4/jTikgTYWlewoGY/bZhYmBvRIK3EB3kXSKAAyHPiSmV8uwRuUEuaZXBNlz8ta1FZAJb5OsVfwA88QP/4xLdi+V7OP9rz5uT0Org3PVnSnRM6kQ5O9jRW2IadTro6JMBHCsmx5EeiIetC3h7eu8nPshg+z00PtdVzhQhrmSaUTtHP8/S0OVaKzipTAu1b6FDIfpxTD/pBgQxG6TaDdLkfzLyyM9xIehFZ0MWP9te34B5idXmhHNACFt2wjpl40roXNbkhBt7Q73gAZwl5UdrEqVEv4eZQhgZL01lK6mh1BqfsNoSXlJXfN2zglHP80ujPWi7cu/fQ2ntos0528K8yflIdR/lR7RYlmGItziqawVChRespnMZsPvawXAYo8nnoEkzSKYtWxigL0vV21+cAxAOYb9WPK/BnMfGMuyI4BPDT/oqj6MiuDXUOnM+/JytgU1mrAo=
  on:
    tags: true
    repo: cphyc/astrophysics_toolset
    python: 3.8
