[build-system]
requires = [
   "setuptools>=19.6",
   "wheel",
   "Cython>=0.29.21",
   "oldest-supported-numpy",
]

[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.isort]
profile = "black"
combine_as_imports = true
skip =  []
known_third_party = [
  "IPython",
  "nose",
  "numpy",
  "sympy",
  "matplotlib",
  "unyt",
  "git",
  "yaml",
  "dateutil",
  "requests",
  "coverage",
  "pytest",
  "pyx",
  "glue",
  "yt"
]
known_first_party = ["astrophysics_toolset"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
